### ISSUE TITLE
Confluence migration isn't working locally on a Windows 11 Pro machine - "Failed to read package"

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-confluence-migrator-pro#121]
When trying to do a Confluence migration. locally, using XWiki 15.10.8, Confluence Migrator Application (Pro) 1.16.1,  Pro Macros 1.16.5 and Chrome 123 on a Windows 11 Pro machine I get the following errors

![ErrorsMigration](https://github.com/xwikisas/application-confluence-migrator-pro/assets/40691112/d0a3feda-b3f8-4212-ac3f-7f82e7a38aac)

```
4/17/2024 10:44:42 AM Failed to read package
org.xwiki.filter.FilterException: Failed to analyze the package index
	at org.xwiki.contrib.confluence.filter.input.ConfluenceXMLPackage.read(ConfluenceXMLPackage.java:743)
	at org.xwiki.contrib.confluence.filter.internal.input.ConfluenceInputFilterStream.readInternal(ConfluenceInputFilterStream.java:310)
	at org.xwiki.contrib.confluence.filter.internal.input.ConfluenceInputFilterStream.read(ConfluenceInputFilterStream.java:198)
	at org.xwiki.contrib.confluence.filter.internal.input.ConfluenceInputFilterStream.read(ConfluenceInputFilterStream.java:100)
	at org.xwiki.filter.input.AbstractBeanInputFilterStream.read(AbstractBeanInputFilterStream.java:79)
	at org.xwiki.filter.internal.job.FilterStreamConverterJob.runInternal(FilterStreamConverterJob.java:97)
	at org.xwiki.job.AbstractJob.runInContext(AbstractJob.java:246)
	at org.xwiki.job.AbstractJob.run(AbstractJob.java:223)
	at org.xwiki.filter.script.internal.ScriptFilterStreamConverterJob.run(ScriptFilterStreamConverterJob.java:75)
	at com.xwiki.confluencepro.internal.ConfluenceMigrationJob.runInternal(ConfluenceMigrationJob.java:163)
	at org.xwiki.job.AbstractJob.runInContext(AbstractJob.java:246)
	at org.xwiki.job.AbstractJob.run(AbstractJob.java:223)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)
Caused by: org.apache.commons.configuration2.ex.ConfigurationException: Cannot create path: C:\Users\Gabriela\AppData\Local\Temp\jetty-0_0_0_0-8080-xwiki-_xwiki-any-11828954906221276193\xwiki-temp\confluencexml-tree16967567752126087313\userimpls\557058:403042db-7e36-4f27-8739-b3f5fef3d15d
	at org.apache.commons.configuration2.io.DefaultFileSystem.createPath(DefaultFileSystem.java:206)
	at org.apache.commons.configuration2.io.DefaultFileSystem.getOutputStream(DefaultFileSystem.java:95)
	at org.apache.commons.configuration2.io.DefaultFileSystem.getOutputStream(DefaultFileSystem.java:65)
	at org.apache.commons.configuration2.io.FileHandler.save(FileHandler.java:988)
	at org.apache.commons.configuration2.io.FileHandler.save(FileHandler.java:896)
	at org.apache.commons.configuration2.io.FileHandler.save(FileHandler.java:850)
	at org.apache.commons.configuration2.builder.FileBasedConfigurationBuilder.save(FileBasedConfigurationBuilder.java:193)
	at org.xwiki.contrib.confluence.filter.input.ConfluenceProperties.save(ConfluenceProperties.java:85)
	at org.xwiki.contrib.confluence.filter.input.ConfluenceXMLPackage.saveObjectProperties(ConfluenceXMLPackage.java:2252)
	at org.xwiki.contrib.confluence.filter.input.ConfluenceXMLPackage.readUserImplObject(ConfluenceXMLPackage.java:1537)
	at org.xwiki.contrib.confluence.filter.input.ConfluenceXMLPackage.readObject(ConfluenceXMLPackage.java:1215)
	at org.xwiki.contrib.confluence.filter.input.ConfluenceXMLPackage.createTree(ConfluenceXMLPackage.java:1157)
	at org.xwiki.contrib.confluence.filter.input.ConfluenceXMLPackage.read(ConfluenceXMLPackage.java:741)
	... 14 more
4/17/2024 10:44:42 AM Exception thrown during job execution
org.xwiki.filter.FilterException: Failed to read package
	at org.xwiki.contrib.confluence.filter.internal.input.ConfluenceInputFilterStream.readInternal(ConfluenceInputFilterStream.java:319)
	at org.xwiki.contrib.confluence.filter.internal.input.ConfluenceInputFilterStream.read(ConfluenceInputFilterStream.java:198)
	at org.xwiki.contrib.confluence.filter.internal.input.ConfluenceInputFilterStream.read(ConfluenceInputFilterStream.java:100)
	at org.xwiki.filter.input.AbstractBeanInputFilterStream.read(AbstractBeanInputFilterStream.java:79)
	at org.xwiki.filter.internal.job.FilterStreamConverterJob.runInternal(FilterStreamConverterJob.java:97)
	at org.xwiki.job.AbstractJob.runInContext(AbstractJob.java:246)
	at org.xwiki.job.AbstractJob.run(AbstractJob.java:223)
	at org.xwiki.filter.script.internal.ScriptFilterStreamConverterJob.run(ScriptFilterStreamConverterJob.java:75)
	at com.xwiki.confluencepro.internal.ConfluenceMigrationJob.runInternal(ConfluenceMigrationJob.java:163)
	at org.xwiki.job.AbstractJob.runInContext(AbstractJob.java:246)
	at org.xwiki.job.AbstractJob.run(AbstractJob.java:223)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)
Caused by: org.xwiki.filter.FilterException: Failed to analyze the package index
	at org.xwiki.contrib.confluence.filter.input.ConfluenceXMLPackage.read(ConfluenceXMLPackage.java:743)
	at org.xwiki.contrib.confluence.filter.internal.input.ConfluenceInputFilterStream.readInternal(ConfluenceInputFilterStream.java:310)
	... 13 more
Caused by: org.apache.commons.configuration2.ex.ConfigurationException: Cannot create path: C:\Users\Gabriela\AppData\Local\Temp\jetty-0_0_0_0-8080-xwiki-_xwiki-any-11828954906221276193\xwiki-temp\confluencexml-tree16967567752126087313\userimpls\557058:403042db-7e36-4f27-8739-b3f5fef3d15d
	at org.apache.commons.configuration2.io.DefaultFileSystem.createPath(DefaultFileSystem.java:206)
	at org.apache.commons.configuration2.io.DefaultFileSystem.getOutputStream(DefaultFileSystem.java:95)
	at org.apache.commons.configuration2.io.DefaultFileSystem.getOutputStream(DefaultFileSystem.java:65)
	at org.apache.commons.configuration2.io.FileHandler.save(FileHandler.java:988)
	at org.apache.commons.configuration2.io.FileHandler.save(FileHandler.java:896)
	at org.apache.commons.configuration2.io.FileHandler.save(FileHandler.java:850)
	at org.apache.commons.configuration2.builder.FileBasedConfigurationBuilder.save(FileBasedConfigurationBuilder.java:193)
	at org.xwiki.contrib.confluence.filter.input.ConfluenceProperties.save(ConfluenceProperties.java:85)
	at org.xwiki.contrib.confluence.filter.input.ConfluenceXMLPackage.saveObjectProperties(ConfluenceXMLPackage.java:2252)
	at org.xwiki.contrib.confluence.filter.input.ConfluenceXMLPackage.readUserImplObject(ConfluenceXMLPackage.java:1537)
	at org.xwiki.contrib.confluence.filter.input.ConfluenceXMLPackage.readObject(ConfluenceXMLPackage.java:1215)
	at org.xwiki.contrib.confluence.filter.input.ConfluenceXMLPackage.createTree(ConfluenceXMLPackage.java:1157)
	at org.xwiki.contrib.confluence.filter.input.ConfluenceXMLPackage.read(ConfluenceXMLPackage.java:741)
	... 14 more
```

**Comment by trrenty** [comment]
Closed by this commit https://github.com/xwikisas/application-confluence-migrator-pro/commit/8f8af607badfbe4308c26cdc3bb9ccbe4a013444
